language: julia
    - 1.0
    - 1.1
    - 1.2
    - 1.4
    - nightly
jobs:
    include:
    - os: linux
      dist: xenial
      before_install: sudo apt-get install -y libhwloc5
    - os: linux
      dist: bionic
      before_install: sudo apt-get install -y libhwloc5
    - os: osx
